### ISSUE TITLE
How to build?

### ISSUE THREAD

**Issue by Panahi2** [KambizAsadzadeh/CuteMobile#4]
How to configure cmake? Change many options but don't get result.

**Comment by thecompez** [comment]
- CMake 3.23 or higher is required.
- Qt 6.x or higher is required.
```
cd build
cmake ..
make
./CuteMobile
```

**Comment by Panahi2** [comment]
There are many options in cmake ...
Please specify which option should be selected

**Comment by thecompez** [comment]
> There are many options in cmake ... Please specify which option should be selected

You don't need any special options for this project.
Please open the Qt Creator IDE and then open CMakeLists.txt file and then choose a suitable kit in this section and build it for your own device.

**Comment by Panahi2** [comment]
### Enviroment:
Ubuntu 22.04
QtCreator 10.0.0
Qt 6.4.2

### Error
```
CuteMobile/source/system.hpp:4: error: QObject: No such file or directory
In file included from CuteMobile/source/system.cpp:1:
CuteMobile/source/system.hpp:4:10: fatal error: QObject: No such file or directory
    4 | #include <QObject>
      |          ^~~~~~~~~
```

**Comment by thecompez** [comment]
Seems there is a some issue with version 6.4.2.
If you can, check with Qt 6.4.3 or later 6.5.
Also an update was applied and I recommend re-downloading the repository.
